# Generated by Django 5.2.5 on 2025-08-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_rename_added_at_wishlistitem_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='created_at',
            new_name='added_at',
        ),
    ]
