# Generated by Django 5.2.5 on 2025-09-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='application_role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'super admin'), ('VENDOR', 'vendor'), ('INFLUENCER', 'influencer'), ('CUSTOMER', 'customer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='application_status',
            field=models.CharField(choices=[('NONE', 'none'), ('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='NONE', max_length=20),
        ),
    ]
