# Generated by Django 5.2.5 on 2025-09-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_application_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='vendors/certificates/'),
        ),
        migrations.AddField(
            model_name='user',
            name='gov_id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
