# Generated by Django 5.2.5 on 2025-08-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailotp_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='application_role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'super admin'), ('VENDOR', 'vendor'), ('INFLUENCER', 'influencer'), ('CUSTOMER', 'customer')], editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='application_status',
            field=models.CharField(choices=[('NONE', 'none'), ('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='NONE', editable=False, max_length=20),
        ),
    ]
