# Generated by Django 5.2.5 on 2025-09-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
        ('products', '0003_product_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adslot',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_slots', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='sponsoredlisting',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_listings', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='sponsoredlisting',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_listings', to='products.product'),
        ),
    ]
