# Generated by Django 5.2.5 on 2025-09-09 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate', '0002_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelink',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsoredlisting',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_listings', to='products.brand'),
        ),
        migrations.AddField(
            model_name='sponsoredlisting',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_listings', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsoredlisting',
            unique_together={('slot_position', 'brand')},
        ),
    ]
