# Generated by Django 5.2.5 on 2025-09-09 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('social_links', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promote_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
