# Generated by Django 5.2.5 on 2025-08-21 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influencers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'INFLUENCER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='influencerproduct',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_products', to='influencers.influencer'),
        ),
        migrations.AddField(
            model_name='influencerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_by', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='influencerproduct',
            unique_together={('influencer', 'product')},
        ),
    ]
