# Generated by Django 5.2.5 on 2025-09-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='region',
            field=models.CharField(default='global', max_length=100),
        ),
    ]
