# Generated by Django 5.2.5 on 2025-10-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='like',
            name='content_type',
            field=models.CharField(max_length=90),
        ),
    ]
