# Generated by Django 5.2.5 on 2025-09-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField()),
                ('hero_image_url', models.URLField(blank=True, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('tags', models.JSONField(default=list, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excerpt', models.TextField(blank=True, max_length=300, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
