# Generated by Django 5.2.5 on 2025-09-09 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role__in': ['INFLUENCER', 'SUPER_ADMIN']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='blogarticle',
            index=models.Index(fields=['slug'], name='blog_blogar_slug_f79c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='blogarticle',
            index=models.Index(fields=['created_at'], name='blog_blogar_created_5ed576_idx'),
        ),
    ]
