# Generated by Django 5.2.5 on 2025-09-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='blogs/videos/'),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
