# Generated by Django 5.2.5 on 2025-09-07 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogarticle_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='excerpt',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='blogarticle',
            index=models.Index(fields=['slug'], name='blog_blogar_slug_f79c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='blogarticle',
            index=models.Index(fields=['created_at'], name='blog_blogar_created_5ed576_idx'),
        ),
    ]
