# Generated by Django 5.2.5 on 2025-09-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogarticle_options_blogarticle_excerpt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogarticle',
            old_name='published',
            new_name='is_published',
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
