# Generated by Django 5.2.5 on 2025-09-06 12:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, null=True)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'city', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField()),
                ('experience_level', models.PositiveIntegerField(choices=[(1, '1-2 years (Emerging Stylist)'), (2, '2-4 years (Skilled Stylist)'), (4, '4-7 years (Senior Stylist)'), (7, '7-8 years (Master Stylist)'), (9, '9-12 years (Artistic Director Level)'), (12, '12-15 years (Creative Director)'), (15, '16+ years (Industry Icon)')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_salon', to='salons.salon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
