# Generated by Django 5.2.5 on 2025-09-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
