# Generated by Django 5.2.5 on 2025-09-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
